### ISSUE TITLE
Comparison with existing packages

### ISSUE THREAD

**Issue by dandv** [nosuchip/mongoose-track#1]
Hi,

At the time when this package was published (2018), there was already a mongoose plugin with the same goal, @nassor's [mongoose-history](https://github.com/nassor/mongoose-history).

How does this package aim to be different from the previously existing one, and what motivated its creation?

**Comment by nosuchip** [comment]
@dandv I maintaining this package after previous owner abandon it. Main goal of this package is to store document's history under object itself rather then in another collection. I knew about `mongoose-history` existence but for my purpose at that moment history must be stored in same document. Unfortunately `mongoose-track` contained number of bugs which prevents me from using it as is. So I continued maintenance of `mongoose-track` from abandoned state.

Reason of such and old last commit is simple: this package covers all my needs, stable and nobody asked for changes/reported bugs.
